### ISSUE TITLE
Can't publish to npm

### ISSUE THREAD

**Issue by shirakaba** [nodegui/svelte-nodegui-preprocessor#2]
Not sure why this isn't working, but I think we ran into it when first publishing `@nodegui/svelte-nodegui`. I thought that now my npm account is a member of the `@nodegui` npm organisation, I'd be able to publish a package with this name.

@a7ul Any ideas?

```sh
$ npm publish --access=public

> @nodegui/svelte-nodegui-preprocessor@0.1.0-alpha prepare .
> npm run build


> @nodegui/svelte-nodegui-preprocessor@0.1.0-alpha build /Users/jamie/Documents/git/svelte-nodegui-preprocessor
> rollup -c


src/index.ts → dist/index.js...
created dist/index.js in 3.4s
npm notice 
npm notice 📦  @nodegui/svelte-nodegui-preprocessor@0.1.0-alpha
npm notice === Tarball Contents === 
npm notice 2.2kB   LICENSE         
npm notice 911.1kB dist/index.js   
npm notice 1.5kB   package.json    
npm notice 1.1kB   CHANGELOG.md    
npm notice 1.2kB   README.md       
npm notice 358B    types/index.d.ts
npm notice === Tarball Details === 
npm notice name:          @nodegui/svelte-nodegui-preprocessor    
npm notice version:       0.1.0-alpha                             
npm notice package size:  181.6 kB                                
npm notice unpacked size: 917.5 kB                                
npm notice shasum:        7bca7d80f8786ab2c8d8155ddf06eb9c7ffdd6b2
npm notice integrity:     sha512-nj2hCmmw9t/67[...]kILBe4mtERipA==
npm notice total files:   6                                       
npm notice 
npm ERR! code E404
npm ERR! 404 Not Found - PUT https://registry.npmjs.com/@nodegui%2fsvelte-nodegui-preprocessor - Not found
npm ERR! 404 
npm ERR! 404  '@nodegui/svelte-nodegui-preprocessor@0.1.0-alpha' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jamie/.npm/_logs/2021-03-03T21_07_32_379Z-debug.log
```

**Comment by a7ul** [comment]
strange. 
I tried now and could publish it

**Comment by a7ul** [comment]
Maybe you can try again ?

**Comment by shirakaba** [comment]
@a7ul thanks! That might make it work from now on, in any case.

I’ll revisit this tomorrow – time for evening games 🎮

**Comment by shirakaba** [comment]
Had a spare moment, so tried again just now. Seems I'd been logged out of npm in the command line; `npm login` resolved it. Quite possibly one of my shells is logged in while another isn't, or something – or my session just expired. No idea. Anyway, I'm able to publish now!

**Comment by nothingismagick** [comment]
Just in case you decide you want to do this all from the CI - check out https://github.com/jbolda/covector - it will do your changelog management and give you a vetted way to publish to npm without having the human maintainer busfactor involved... We built it (well @jbolda built it) for Tauri, but its really useful!!!

**Comment by shirakaba** [comment]
@nothingismagick Thanks for this!

I think `svelte-nodegui-preprocessor` may have already reached its final state, but I'll certainly keep covector in mind for the Svelte NodeGUI main repo. I do like the sounds of reducing stresses on the human maintainer (me), and if it's made sense for Tauri it should make sense for Svelte NodeGUI as well.

That said, reading through [the README](https://github.com/jbolda/covector/tree/main/packages/covector), I'm rather unclear what the workflow is for using this. e.g.

– When and where would I write my changelog entry?
– How would I use this to make a new release in GitHub's "releases" tab?
– How would I provide it with an API key for my GitHub user?
– Is there a step-by-step example walkthrough of the process for making a change, and then publishing a release?

I'm also unclear of this bit:

> As you create PRs and make changes that require a version bump, please add a new markdown file in this folder.

Is this talking about creating PRs for Covector itself, or against my own projects? And what's "this folder"? Also, what's an example file name for it?

I'm not used to change management beyond manual commit messages, changelog changes, and invoking `npm publish`. So I'd personally need a lot more hand-holding to get to grips with a managed tool!

**Comment by nothingismagick** [comment]
At tauri we use feature branches and PR to dev. In a feature PR we add a file at e.g. `.changes/my-change.md` with contents like you can see here: https://github.com/tauri-apps/tauri/blob/dev/.changes/appimage-path.md

These changes get collected, in a long-lived PR here: https://github.com/tauri-apps/tauri/pull/1165

You can see we are preparing a MASSIVE beta release. Now, all these changes then get placed in their respective crate changelogs. ...

If you want more info, then by all means stop by our discord and ping me. :)
